#!/bin/sh -l
# FILENAME:  task_all.sub

#PBS -l nodes=1:ppn=1
#PBS -q long

cd $PBS_O_WORKDIR

module load rcac

mpiexec -n 1 ./task1


#PBS -l nodes=1:ppn=2
#PBS -q long

cd $PBS_O_WORKDIR

module load rcac

mpiexec -n 2 ./task1


#PBS -l nodes=1:ppn=4
#PBS -q long

cd $PBS_O_WORKDIR

module load rcac

mpiexec -n 4 ./task1


#PBS -l nodes=2:ppn=8
#PBS -q long

cd $PBS_O_WORKDIR

module load rcac

mpiexec -n 8 ./task1


#PBS -l nodes=4:ppn=16
#PBS -q long

cd $PBS_O_WORKDIR

module load rcac

mpiexec -n 16 ./task1


#PBS -l nodes=1:ppn=1
#PBS -q long

cd $PBS_O_WORKDIR

module load rcac

mpiexec -n 1 ./task2


#PBS -l nodes=1:ppn=4
#PBS -q long

cd $PBS_O_WORKDIR

module load rcac

mpiexec -n 4 ./task2


#PBS -l nodes=4:ppn=16
#PBS -q long

cd $PBS_O_WORKDIR

module load rcac

mpiexec -n 16 ./task2


#PBS -l nodes=1:ppn=1
#PBS -q long

cd $PBS_O_WORKDIR

module load intel

./task3


#PBS -l nodes=1:ppn=2
#PBS -q long

cd $PBS_O_WORKDIR

module load intel

./task3


#PBS -l nodes=1:ppn=4
#PBS -q long

cd $PBS_O_WORKDIR

module load intel

./task3


#PBS -l nodes=2:ppn=8
#PBS -q long

cd $PBS_O_WORKDIR

module load intel

./task3


#PBS -l nodes=4:ppn=16
#PBS -q long

cd $PBS_O_WORKDIR

module load intel

./task3